<!DOCTYPE html>
<html lang="pt-BR">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Tatiana Camargo - Página Pessoal</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 0;
            padding: 0;
            background-color: #ffffff;
            color: #333333;
        }
        .container {
            max-width: 800px;
            margin: 0 auto;
            padding: 20px;
        }
        h1 {
            color: #009900;
        }
        img {
            max-width: 100%;
            height: auto;
            border-radius: 50%;
            margin-bottom: 20px;
        }
        h2 {
            color: #009900;
        }
        ul {
            list-style-type: none;
            padding: 0;
        }
        li {
            margin-bottom: 10px;
        }
        a {
            color: #009900;
            text-decoration: none;
        }
        a:hover {
            text-decoration: underline;
        }
    </style>
</head>
<body>
    <div class="container">
        <img src="link_para_sua_imagem_de_perfil.jpg" alt="Imagem de perfil">
        <h1>Tatiana Camargo</h1>

        <h2>Sobre Mim</h2>
        <p>Olá! Sou Tatiana Camargo, apaixonada por podologia e dedicada a proporcionar cuidados especiais para os pés. Minha jornada nesse campo começou há [tempo] anos, e desde então tenho buscado aprimorar meus conhecimentos e habilidades para oferecer os melhores tratamentos e soluções para os meus clientes.</p>
        <p>Além da podologia, tenho interesse em [inserir outros interesses ou hobbies, se houver].</p>

        <h2>Serviços</h2>
        <ul>
            <li>Corte e Higienização de Unhas</li>
            <li>Tratamento de Calos e Calosidades</li>
            <li>Remoção de Calos Plantares</li>
            <li>Tratamento de Unhas Encravadas</li>
            <li>Avaliação e Orientação para Problemas Podológicos</li>
        </ul>

        <h2>Contato</h2>
        <p>Para agendar uma consulta ou obter mais informações sobre os serviços oferecidos, entre em contato comigo pelos seguintes meios:</p>
        <ul>
            <li>Telefone: [Inserir número de telefone]</li>
            <li>E-mail: [Inserir endereço de e-mail]</li>
            <li>Endereço: [Inserir endereço do consultório, se aplicável]</li>
        </ul>

        <h2>Horário de Atendimento</h2>
        <p>Segunda a Sexta: [Inserir horário de atendimento]</p>
        <p>Sábado: [Inserir horário de atendimento, se aplicável]</p>
        <p>Domingo: Fechado</p>

        <h2>Redes Sociais</h2>
        <p>Siga-me nas redes sociais para ficar por dentro das últimas novidades e dicas sobre cuidados com os pés:</p>
        <ul>
            <li><a href="link_para_perfil_do_instagram">Instagram</a></li>
            <li><a href="link_para_pagina_do_facebook">Facebook</a></li>
        </ul>

        <h2>Testemunhos de Clientes</h2>
        <p>*Aqui você pode adicionar depoimentos de clientes satisfeitos com os seus serviços.*</p>
    </div>
</body>
</html>

